webtalk_init -webtalk_dir D:/2021/DE1_GIT/Digital-electronics-1/Labs/03-vivado/mux_2bit_4to1/mux_2bit_4to1.sim/sim_1/behav/xsim/xsim.dir/tb_mux_2bit_4to1_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar  1 12:34:03 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "47cd29ed-35bd-4458-936c-63f9cb2a993e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5590e0c282b24e7b9c5f3db70305e933" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2400G with Radeon Vega Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3593 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5964_KB" -context "xsim\\usage"
webtalk_transmit -clientid 864159485 -regid "" -xml D:/2021/DE1_GIT/Digital-electronics-1/Labs/03-vivado/mux_2bit_4to1/mux_2bit_4to1.sim/sim_1/behav/xsim/xsim.dir/tb_mux_2bit_4to1_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/2021/DE1_GIT/Digital-electronics-1/Labs/03-vivado/mux_2bit_4to1/mux_2bit_4to1.sim/sim_1/behav/xsim/xsim.dir/tb_mux_2bit_4to1_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/2021/DE1_GIT/Digital-electronics-1/Labs/03-vivado/mux_2bit_4to1/mux_2bit_4to1.sim/sim_1/behav/xsim/xsim.dir/tb_mux_2bit_4to1_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
